#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "csv-to-db"
main = "main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "igor-brasileiro-s-60"

[assets]
directory = "./view-build"
binding = "ASSETS"

[deco]
workspace = "igor-brasileiro-s-60"
enable_workflows = true
local = false

[[deco.bindings]]
name = "DATABASES"
type = "mcp"
integration_id = "i:databases-management"

[[deco.bindings]]
name = "GMAIL"
type = "mcp"
integration_name = "@deco/google-gmail"

[[migrations]]
tag = "v1"
new_classes = [ "Workflow" ]

[durable_objects]
[[durable_objects.bindings]]
name = "DECO_CHAT_WORKFLOW_DO"
class_name = "Workflow"